version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    #volumes:
    #  - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
  app:
    image: hypechat:1.0
    container_name: hypechat-serverapp
    build: .
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - .env
        #- PORT=3030
    # command: bash -c "npm test"
    command: bash -c "node index.js"
